
---

- name: Download oh-my-zsh installer
  get_url: url=https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh dest=/tmp/oh-my-zsh-installer.sh

- name: Changing perm of "/tmp/oh-my-zsh-installer.sh", adding "+x"
  file: dest=/tmp/oh-my-zsh-installer.sh mode=u+x

- name: Execute the oh-my-zsh-installer.sh
  shell: /tmp/oh-my-zsh-installer.sh
  ignore_errors: yes 
  
- name: Remove the oh-my-zsh-installer.sh
  file: path=/tmp/oh-my-zsh-installer.sh state=absent

- name: Clone p10k
  git: 
    repo: git@github.com:romkatv/powerlevel10k.git
    dest: ~/powerlevel10k
    depth: 1
